language: c

sudo: false

matrix:
  include:
  - env: ARGS="--stack-yaml stack-ghc-7.10.3.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS="--stack-yaml stack-ghc-8.0.2.yaml"
    addons: {apt: {packages: [libgmp-dev]}}

  - env: ARGS=
    addons: {apt: {packages: [libgmp-dev]}}

cache:
  directories:
  - $HOME/.stack

before_install:
- export PATH=$HOME/.local/bin:$PATH;
  mkdir -p ~/.local/bin;
  travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
  stack --version

install:
- stack $ARGS setup --no-terminal;
  stack $ARGS build --no-terminal --only-snapshot --test --no-run-tests;

script:
- export ARG='--test-arguments'
  export TEST_PACKAGE="distributed-process-tests:"
- stack ${ARGS} test $ARG='--plain -t "!Flaky"' ${TEST_PACKAGE}TestCHInMemory
- stack ${ARGS} test $ARG='--plain -t "!Flaky"' ${TEST_PACKAGE}TestCHInTCP
- stack ${ARGS} test $ARG='--plain -t "!SpawnReconnect"' ${TEST_PACKAGE}TestClosure
- stack ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestStats
- stack ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestMx
- stack ${ARGS} test $ARG='--plain' ${TEST_PACKAGE}TestTracing
