resolver: nightly-2017-08-20

# TODO: we can enable nightly-2018-11-11 once PR #319 is merged

packages:
- '.'
- distributed-process-tests/

extra-deps:
- rank1dynamic-0.4.0
- distributed-static-0.3.8
- network-transport-0.5.2
- network-transport-tcp-0.6.0
- network-transport-inmemory-0.5.2
- rematch-0.2.0.0

flags:
  distributed-process-tests:
    tcp: true
